name: Mirror to GitVerse

on: [push, delete]

jobs:
  gitverse-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitVerse
        run: |
          git push --prune --force https://${{ secrets.GITVERSE }}@gitverse.ru/moyunni/chiplay.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
